export const AUTH_FAIL='AUTH_FAIL';
export const AUTH_SUCCESS='AUTH_SUCCESS';
export const AUTH_LOGOUT= 'AUTH_LOGOUT';
export const AUTH_AUTOLOGIN_SUCCESS='AUTH_AUTOLOGIN_SUCCESS';
export const AUTH_SET_LOCATION='AUTH_SET_LOCATION';