export const AUTH_FAIL='AUTH_FAIL';
export const AUTH_SUCCESS='AUTH_SUCCESS';
export const AUTH_LOGOUT= 'AUTH_LOGOUT';
export const AUTH_AUTOLOGIN_SUCCESS='AUTH_AUTOLOGIN_SUCCESS';
export const AUTH_SET_LOCATION='AUTH_SET_LOCATION';

export const NOTIFY_GETLIST='NOTIFY_GETLIST';
export const NOTITY_GETLIST_SUCCESS = 'NOTITY_GETLIST_SUCCESS'

export const PERMISSION_GET ='PERMISSION_GET';
export const PERMISSION_GET_SUCCESS ='PERMISSION_GET_SUCCESS';
export const PERMISSION_GET_FAIL ='PERMISSION_GET_FAIL';